version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build: .
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/automation
    depends_on:
      - mongo
